# Generated by Django 3.2 on 2021-05-04 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
