# Generated by Django 3.2 on 2021-05-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_todolist_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='important',
            field=models.BooleanField(default=False),
        ),
    ]
